services:
  - type: web
    name: journal-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx256m -Xms128m -XX:+UseG1GC -XX:+UseContainerSupport -Dspring.profiles.active=prod"
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx256m -Xms128m -XX:+UseG1GC -XX:+UseContainerSupport -Dspring.profiles.active=prod -jar target/*.jar
