services:
  - type: web
    name: journal-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseContainerSupport -jar target/*.jar
