spring:
  profiles:
    active: dev

weather:
  api:
    key: ${WEATHER_API_KEY}
#logging:
#  level:
#    com:
#      karna:
#        ankur:
#          Journal: TRACE
#logging:
#  level:
#    root: ERROR
