spring:
  data:
    mongodb:
      uri: mongodb+srv://ankurkarna:xV4s5CCSJJQEjnQz@cluster0.ih67exj.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  application:
    name: Journal
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    context-path:
