spring:
  profiles:
   active: dev


weather:
  api:
    key: ec3c3be61ae9e833ea3f7d679382da38

#logging:
#  level:
#    com:
#      karna:
#        ankur:
#          Journal: TRACE
#logging:
#  level:
#    root: ERROR