spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  application:
    name: Journal
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  port: 8081
  servlet:
    context-path:
